In [89]:
import pandas as pd
import pickle
from sklearn.preprocessing import StandardScaler


test_data_file_name='test__comments_data_set.csv'
train_data_file_name='train__comments_data_set.csv'
model_filename='comments_prediction_model.sav'

test=pd.read_csv(test_data_file_name)
train=pd.read_csv(train_data_file_name)

del test['Unnamed: 0']
del train['Unnamed: 0']

loaded_model = pickle.load(open(model_filename, 'rb'))

In [90]:
x_test_data=test[test.columns[:-1]]
y_test_data=test[test.columns[-1]]
x_train_data=train[train.columns[:-1]]
y_train_data=train[train.columns[-1]]

In [91]:
sc_X = StandardScaler()
x_train = sc_X.fit_transform(x_train_data)
x_test = sc_X.transform(x_test_data)

sc_Y = StandardScaler()
y_train=y_train_data.values.reshape(-1,1)
sc_Y.fit_transform(y_train)
y_train=sc_Y.transform(y_train)
y_test=y_test_data.values.reshape(-1,1)
y_test=sc_Y.transform(y_test)

In [92]:
pred = loaded_model.predict(x_test)
predicated_value = sc_Y.inverse_transform(pred.reshape(-1,1)).reshape(-1)

In [93]:
x_test_data['pred_value']=predicated_value
x_test_data

,No_of_Hashtags,followers,day_of_week,username,Avg_comments,Post_Sentiments,Time_of_day,post_type,brightness,face_detection,pred_value
0,1,451103,5,371,74.859375,1,1,0,False,1,74.003444
1,5,451103,6,371,74.859375,0,4,0,False,1,75.819482
2,1,451103,1,371,74.859375,1,1,0,False,1,74.671289
3,1,451103,6,371,74.859375,1,4,1,False,1,75.819482
4,1,451103,2,371,74.859375,1,4,0,False,1,75.291822
...,...,...,...,...,...,...,...,...,...,...,...
2617,1,9406,5,233,18.823529,1,0,1,False,1,16.639126
2618,4,9406,5,233,18.823529,0,3,3,False,1,16.639126
2619,1,9406,6,233,18.823529,1,1,3,False,1,16.639126
2620,1,9406,6,233,18.823529,0,3,0,False,1,16.639126
2621,1,9406,0,233,18.823529,1,0,0,False,1,16.639126